[versions]
kotlin = "1.6.10"
kotlinx-coroutines = "1.6.1"
kotest = "5.2.3"
kodein = "7.11.0"

[libraries]

# plugins

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# kotlinx

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# others

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kodein = { module = "org.kodein.di:kodein-di", version.ref = "kodein"}